// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile() {
  return window['go']['apps']['App']['ChooseFile']();
}

export function Confirm(arg1) {
  return window['go']['apps']['App']['Confirm'](arg1);
}

export function DomReady(arg1) {
  return window['go']['apps']['App']['DomReady'](arg1);
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}
