// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile() {
  return window['go']['apps']['App']['ChooseFile']();
}

export function ConfirmAddFile(arg1) {
  return window['go']['apps']['App']['ConfirmAddFile'](arg1);
}

export function CreatTask(arg1) {
  return window['go']['apps']['App']['CreatTask'](arg1);
}

export function GetFileList() {
  return window['go']['apps']['App']['GetFileList']();
}

export function Greet(arg1) {
  return window['go']['apps']['App']['Greet'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['apps']['App']['RemoveFile'](arg1);
}
